### ISSUE TITLE
Map tiles on large map exports not getting rendered

### ISSUE THREAD

**Issue by bsherman101** [MesseBasseProduction/MesseMap#10] opened 2023-04-13 13:42 UTC
Very impressive work and thank you for making this available.

I was playing around with it on messemap.org and am interested in high resolution maps.

Pretty much everytime I export I never get a complete map.  Tiles will be missing as if they are not being loaded.  I saw you had previous issues on this and tried to fix it but wanted to let you know the problem still persists.

![image](https://user-images.githubusercontent.com/5846007/231777263-18adb100-19a5-43ae-b81c-af117abd1b61.png)

**Comment by ArthurBeaulieu** [comment] 2023-04-13 14:59
Hello [bsherman101](https://github.com/bsherman101),
Thanks for submitting this issue. I'll try to find a better way to avoid this issue ; can you please provide some information to help reproduce ?
Like desktop/mobile, browser, output format, and anything you could find useful ?
I'll try to look at this in the coming weeks, I'll let you know in this issue!
Kind regards.
Arthur

**Comment by bsherman101** [comment] 2023-04-13 20:24
Hi Arthur,

So I was using Chrome Version 112.0.5615.86 (Official Build) (64-bit) on Windows 10 with 8 GB of RAM.

The example above was me trying to export the highest resolution possible in webp format.

After trying a bunch of different scenarios, (i.e. background, zoom level, export size and format) I am still seeing occasional gray squares but not as bad as my initial example.

I've been using messemap.org.  I tried https://messebasseproduction.github.io/MesseMap/index.html and that doesn't produce a map at all.  Your ReadMe I believe indicates that version is not yet working though.

Below are the exports I made and you can see which ones had some gray squares.  These were all at the highest resolution.

Thanks for looking into this.

-Brian

![image](https://user-images.githubusercontent.com/5846007/231874662-f851f6b5-4323-45bd-abad-d91f1a623d43.png)

**Comment by ArthurBeaulieu** [comment] 2023-04-18 13:14
Hello Brian,

Thanks for those information, will give better insight for me to debug this.
You can only use https://messemap.org now, as it require an expressjs server to proxify maps (and allow them to be rendered in canvas without tainting). using https://messebasseproduction.github.io/MesseMap/index.html will result in failing exported map. I'll update the README accordingly.

I'll let you know on this issue as soon as I have a fix.
Kind regards.
Arthur

**Comment by bsherman101** [comment] 2023-04-20 15:49
Hi Arthur,

Thanks for taking a look.

I was looking into this last night and also saw the error you reference above when inspecting within chrome.  It seems for me the error was originating within thml2canvas.

Im now not so sure its the tiles not loading and instead it may be html2canvas running out of resources and and not rendering/converting each image.

Some ideas I had that I wanted to look into...

Leaflet has a tile error event when a tile doesn't load.  Was thinking of trying to have the tile reload if that happens.

I also wanted to look into using puppeteer to render the poster on the server side and avoid the resource limit within the browser.

Just need to find some time to do that.

Thanks again for looking into the problem.

Great work so far.

**Comment by ArthurBeaulieu** [comment] 2023-04-25 08:54
Hello Brian,
Indeed it seems to be a ressources issue.
I'll try to play around with the onerror of Leaflet, if there is any chance to ask again tiles with a timeout to avoid the ressources running out.
The puppeteer can be a great solution to achieve, limiting ressources consumption on the front-end, but I'm don't know the support standing of html2canvas into headless browser. Anyway, it would be a pleasure to have a PR (or to help you out on it) for this topic, new contributors always welcome !
Have a nice day
Arthur

**Comment by ArthurBeaulieu** [comment] 2024-01-22 16:05
Hello @bsherman101 
It's been several month, and before release I've made several changes back loading mechanism. 
I'm unable to reproduce now this issue, can you confirm on your side so I can close ?
Kind regards.
Arthur

**Comment by ArthurBeaulieu** [comment] 2024-07-17 06:49
Closing issue since it hasn't been reproduced in times

**Closed by ArthurBeaulieu** 2024-07-17 06:49 UTC
Labels: bug
